# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop for the latest recommended versions
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.18

# Mod Properties
mod_version=1.0.1
maven_group=com.example
archives_base_name=invite-whitelist

# Dependencies
fabric_api_version=0.152.1+26.2
fabric_permissions_api_version=0.7.0
